/***************************************************************
 * Name:      ERYAProfilingdialogSetup.h
 * Purpose:   ERYA Config Editor headers
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2016-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef ERYAProfilingDIALOGSETUP_H_INCLUDED
#define ERYAProfilingDIALOGSETUP_H_INCLUDED

/**
@file
Subclass of dialogSetup, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing dialogSetup */
class ERYAProfilingdialogSetup : public dialogSetup
{
	protected:
		// Handlers for dialoghelp events.
		void OnDefaultSave( wxCommandEvent& event );
		void OnDefaultReset( wxCommandEvent& event );
		void OnDefaultDelete( wxCommandEvent& event );
		void OnDefaultQuit( wxCommandEvent& event );
		void OnDefaultHelp( wxCommandEvent& event );
	public:
		/** Constructor */
        ERYAProfilingdialogSetup( wxWindow* parent );
	//// end generated class members


};


#endif // ERYAProfilingDIALODSETUP_H_INCLUDED
