#ifndef __ERYAProfilingdialogERYAProfilingAdvanced__
#define __ERYAProfilingdialogERYAProfilingAdvanced__

/**
@file
Subclass of dialogERYAProfilingAdvanced, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing dialogERYAProfilingAdvanced */
class ERYAProfilingdialogERYAProfilingAdvanced : public dialogERYAProfilingAdvanced
{
	protected:
		// Handlers for dialogERYAProfilingAdvanced events.
		void OnAdvancedOK( wxCommandEvent& event );
		void OnAdvancedDefault( wxCommandEvent& event );
		void OnAdvancedCancel( wxCommandEvent& event );
		void OnAdvancedHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingdialogERYAProfilingAdvanced( wxWindow* parent );
	//// end generated class members

};

#endif // __ERYAProfilingdialogERYAProfilingAdvanced__
