#ifndef __ERYAProfilingwizardFirstRun__
#define __ERYAProfilingwizardFirstRun__

/**
@file
Subclass of wizardFirstRun, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing wizardFirstRun */
class ERYAProfilingwizardFirstRun : public wizardFirstRun
{
	protected:
		// Handlers for wizardFirstRun events.
		void OnFirstRunCancel( wxWizardEvent& event );
		void OnFirstRunFinish( wxWizardEvent& event );
	public:
		/** Constructor */
		ERYAProfilingwizardFirstRun( wxWindow* parent );
	//// end generated class members




};

#endif // __ERYAProfilingwizardFirstRun__
