#ifndef __ERYAProfilingwizardLabViewImport__
#define __ERYAProfilingwizardLabViewImport__

/**
@file
Subclass of wizardLabViewImport, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"
#include "DatabaseLibrary.h"

//// end generated include

/** Implementing wizardLabViewImport */
class ERYAProfilingwizardLabViewImport : public wizardLabViewImport
{
	protected:
		// Handlers for wizardLabViewImport events.
		void OnLabViewImportCancel( wxWizardEvent& event );
		void OnLabViewImportFinish( wxWizardEvent& event );
	public:
		/** Constructor */
		ERYAProfilingwizardLabViewImport( wxWindow* parent );
	//// end generated class members




};

#endif // __ERYAProfilingwizardLabViewImport__
