#ifndef __ERYAProfilingdialogRemark__
#define __ERYAProfilingdialogRemark__

/**
@file
Subclass of dialogRemark, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing dialogRemark */
class ERYAProfilingdialogRemark : public dialogRemark
{
	protected:
		// Handlers for dialogRemark events.
		void OnRemarkSave( wxCommandEvent& event );
		void OnRemarkClear( wxCommandEvent& event );
		void OnRemarkQuit( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingdialogRemark( wxWindow* parent, wxString info, int n );
		ERYAProfilingdialogRemark( wxWindow* parent );
	private:
        int FlagValue;
	//// end generated class members

};

#endif // __ERYAProfilingdialogRemark__
