/***************************************************************
 * Name:      ERYAProfilingdialogR33DataImport.h
 * Purpose:   ERYA ITN/R33 Text Data Import Tool implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2017-01-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef ERYAPROFILINGDIALOGR33DATAIMPORT_H_INCLUDED
#define ERYAPROFILINGDIALOGR33DATAIMPORT_H_INCLUDED

/**
@file
Subclass of dialogR33DataImport, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"
//// end generated include

/** Implementing dialogR33DataImport */
class ERYAProfilingdialogR33DataImport : public dialogR33DataImport
{
	protected:
		// Handlers for dialogAddDatabase events.
	void OnDataImportValidate( wxCommandEvent& event );
    void OnDataImportAbort( wxCommandEvent& event );
    void OnDataImportReset( wxCommandEvent& event );
    void OnDataImportHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingdialogR33DataImport( wxWindow* parent);

	//// end generated class members


};

#endif // ERYAPROFILINGDIALOGR33DATAIMPORT_H_INCLUDED
