#ifndef __ERYAProfilingdialogERYAProfilingViewer__
#define __ERYAProfilingdialogERYAProfilingViewer__

/**
@file
Subclass of dialogERYAProfilingViewer, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing dialogERYAProfilingViewer */
class ERYAProfilingdialogERYAProfilingViewer : public dialogERYAProfilingViewer
{
	protected:
		// Handlers for dialogERYAProfilingViewer events.
		void OnEnergyPrevious( wxCommandEvent& event );
		void OnEnergyNext( wxCommandEvent& event );
		void OnLayerMinus( wxCommandEvent& event );
		void OnLayerPlus( wxCommandEvent& event );
		void OnTakeScreenshoot( wxCommandEvent& event );
		void OnViewerQuit( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingdialogERYAProfilingViewer( wxWindow* parent );
		ERYAProfilingdialogERYAProfilingViewer( wxWindow* parent, wxGrid* data );
    private:
        wxGrid* ViewerData;
        int ViewerSlot;
        bool FindSlot(int adress);
        int FindPrevSlot(int adress);
        int FindNextSlot(int adress);
        bool DisplaySlot(int adress);
	//// end generated class members

};

#endif // __ERYAProfilingdialogERYAProfilingViewer__
