/***************************************************************
 * Name:      ERYAProfilingdialogAddDatabase.h
 * Purpose:   ERYA Database Editor implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2015-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef __ERYAProfilingdialogAddDatabase__
#define __ERYAProfilingdialogAddDatabase__

/**
@file
Subclass of dialogAddDatabase, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"
//// end generated include

/** Implementing dialogAddDatabase */
class ERYAProfilingdialogAddDatabase : public dialogAddDatabase
{
	private:
	int Units,Angles,Profile;
	bool IgnoreLine;
	protected:
		// Handlers for dialogAddDatabase events.
		void OnDatabaseSelect( wxGridRangeSelectEvent& event );
		void OnImportR33( wxCommandEvent& event );
		void OnExportR33( wxCommandEvent& event );
		void OnDatabaseCopy( wxCommandEvent& event );
		void OnDatabasePaste( wxCommandEvent& event );
		void OnEditClear( wxCommandEvent& event );
		void OnEditSave( wxCommandEvent& event );
		void OnEditCancel( wxCommandEvent& event );
		void OnEditHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingdialogAddDatabase( wxWindow* parent);
		void SetSelectUnit(int SigmaUnit){Units = SigmaUnit; return;}
	    void SetSelectAngle(int SigmaAngle){Angles = SigmaAngle; return;}
	    void SetSelectMode(int SigmaProfile){Profile = SigmaProfile; return;}
	    void SetIgnoreInvalidLine(bool ParserErrorDisable){IgnoreLine = ParserErrorDisable; return;}

	//// end generated class members




};

#endif // __ERYAProfilingdialogAddDatabase__
