#ifndef __ERYAProfilingwizardSRIMImport__
#define __ERYAProfilingwizardSRIMImport__

/**
@file
Subclass of wizardSRIMImport, which is generated by wxFormBuilder.
*/

#include "ERYAProfiling.h"

//// end generated include

/** Implementing wizardSRIMImport */
class ERYAProfilingwizardSRIMImport : public wizardSRIMImport
{
	protected:
		// Handlers for wizardSRIMImport events.
		void OnSRIMImportCancel( wxWizardEvent& event );
		void OnSRIMImportComplete( wxWizardEvent& event );
		void OnSRIMSourceSelect( wxCommandEvent& event );
		void OnSRIMSourceLoad( wxCommandEvent& event );
		void OnSRIMSourceRemove( wxCommandEvent& event );
		void OnSRIMSourceClear( wxCommandEvent& event );
		void OnEnableZieglerFiles( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAProfilingwizardSRIMImport( wxWindow* parent );
	//// end generated class members


};

#endif // __ERYAProfilingwizardSRIMImport__
